services:
  - type: web
    name: crm-multi
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: staging
      - key: FLASK_APP
        value: app.py
      - key: SECRET_KEY
        generateValue: true
      - key: CSRF_SECRET_KEY
        generateValue: true
      - key: DATABASE_NAME
        value: /data/crm_multi.db
    autoDeploy: true
    healthCheckPath: /
    numInstances: 1
    disk:
      name: crmbase-staging-disk
      mountPath: /data
      sizeGB: 1 