services:
  - type: web
    name: crmbase
    env: python
    buildCommand: |
      chmod +x init.sh
      # Install sqlite3 for database checks
      apt-get update && apt-get install -y sqlite3
      # Create data directory
      mkdir -p /data
      chmod 777 /data
      # Verify data directory
      if [ ! -d "/data" ] || [ ! -w "/data" ]; then
        echo "Error: Data directory setup failed"
        exit 1
      fi
    startCommand: ./init.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        value: sqlite:////data/crm_multi.db
      - key: DATABASE_NAME
        value: /data/crm_multi.db
      - key: FLASK_ENV
        value: staging
      - key: FLASK_APP
        value: app.py
      - key: SECRET_KEY
        generateValue: true
      - key: SQLALCHEMY_DATABASE_URI
        value: sqlite:////data/crm_multi.db
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
      persist: true
    autoDeploy: true
    healthCheckPath: /
    numInstances: 1 
