services:
  - type: web
    name: crm-multi-dev
    env: python
    buildCommand: |
      pip install -r requirements.txt
      echo '#!/bin/bash
      python database_setup.py
      gunicorn -w 1 -b 0.0.0.0:$PORT app:app' > start.sh
      chmod +x start.sh
    startCommand: ./start.sh
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: development
      - key: FLASK_DEBUG
        value: "true"
      - key: SQLALCHEMY_DATABASE_URI
        value: sqlite:////data/crm_multi.db
      - key: SECRET_KEY
        value: dev-secret-key-123
      - key: CSRF_SECRET_KEY
        value: dev-csrf-secret-key-123
      - key: SESSION_COOKIE_SECURE
        value: "false"
    autoDeploy: true
    healthCheckPath: /
    numInstances: 1
    disk:
      name: crmbase-dev-disk
      mountPath: /data
      sizeGB: 1 
