services:
  - type: web
    name: crm-multi
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python database_setup.py
    startCommand: gunicorn -w 1 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: FLASK_ENV
        value: staging
      - key: DATABASE_NAME
        value: /data/crm_multi.db
    autoDeploy: true
    healthCheckPath: /
    numInstances: 1
    disk:
      name: crmbase-staging-disk
      mountPath: /data
      sizeGB: 1 
