services:
  - type: web
    name: crmbase
    env: python
    buildCommand: chmod +x init.sh
    startCommand: ./init.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        value: sqlite:////data/crm_multi.db
      - key: FLASK_ENV
        value: staging
      - key: FLASK_APP
        value: app.py
      - key: SECRET_KEY
        generateValue: true
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
      persist: true
    autoDeploy: true
    healthCheckPath: /
    numInstances: 1 
